services:
  crowd:
    build: .
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    ports:
      - ${CROWD_PORT:-8000}:8000
    volumes:
      - ${AGENTS_DIR:-./agents}:/agents
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - ZOHO_SMTP_EMAIL=${ZOHO_SMTP_EMAIL}
      - ZOHO_SMTP_PASSWORD=${ZOHO_SMTP_PASSWORD}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
