name: akson
services:
  api:
    build:
      context: ./api
    develop:
      watch:
        - path: ./api
          action: sync
          target: /app
          ignore:
            - .venv/
            - chats/
        - path: ./api/pyproject.toml
          action: rebuild
    ports:
      - ${AKSON_API_PORT}:8000
    volumes:
      - ./api/chats:/app/chats
    environment:
      - ALLOW_ORIGINS=${AKSON_WEB_EXTERNAL_URL}
    env_file:
      - ./api/.env

  web:
    build:
      context: ./web
    develop:
      watch:
        - path: ./web
          action: sync
          target: /app
          ignore:
            - node_modules/
        - path: ./askon-web/package.json
          action: rebuild
    ports:
      - ${AKSON_WEB_PORT}:5173
    environment:
      - VITE_API_BASE_URL=${AKSON_API_EXTERNAL_URL}

  cli:
    build:
      context: ./cli
    profiles:
      - cli
    environment:
      - AKSON_API_BASE_URL=http://api:8000
