services:
  backend:
    build: ./backend
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
    ports:
      - 8000:8000
    env_file:
      - .env

  frontend:
    build: ./frontend
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app
    ports:
      - 5173:5173
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
