[tool.poetry]
name = "crowd"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
gradio = "^4.44.0"
pydantic = "^2.9.2"
openai = "^1.46.0"
python-dotenv = "^1.0.1"
uvicorn = "^0.30.6"
sse-starlette = "^2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
