// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chats.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (id, title, assistant, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, title, assistant, created_at, updated_at
`

type CreateChatParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Title     pgtype.Text `db:"title" json:"title"`
	Assistant pgtype.Text `db:"assistant" json:"assistant"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.ID, arg.Title, arg.Assistant)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Assistant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChat, id)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, title, assistant, created_at, updated_at FROM chats WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id pgtype.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Assistant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatSummaries = `-- name: GetChatSummaries :many
SELECT id, 
       COALESCE(title, 'Untitled Chat') as title,
       updated_at as last_updated
FROM chats 
ORDER BY updated_at DESC
`

type GetChatSummariesRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	LastUpdated pgtype.Timestamptz `db:"last_updated" json:"last_updated"`
}

func (q *Queries) GetChatSummaries(ctx context.Context) ([]GetChatSummariesRow, error) {
	rows, err := q.db.Query(ctx, getChatSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatSummariesRow{}
	for rows.Next() {
		var i GetChatSummariesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.LastUpdated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChats = `-- name: GetChats :many
SELECT id, title, assistant, created_at, updated_at FROM chats ORDER BY updated_at DESC
`

func (q *Queries) GetChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Assistant,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChat = `-- name: UpdateChat :one
UPDATE chats 
SET title = $2, assistant = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, title, assistant, created_at, updated_at
`

type UpdateChatParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Title     pgtype.Text `db:"title" json:"title"`
	Assistant pgtype.Text `db:"assistant" json:"assistant"`
}

func (q *Queries) UpdateChat(ctx context.Context, arg UpdateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateChat, arg.ID, arg.Title, arg.Assistant)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Assistant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatAssistant = `-- name: UpdateChatAssistant :one
UPDATE chats 
SET assistant = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, title, assistant, created_at, updated_at
`

type UpdateChatAssistantParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Assistant pgtype.Text `db:"assistant" json:"assistant"`
}

func (q *Queries) UpdateChatAssistant(ctx context.Context, arg UpdateChatAssistantParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateChatAssistant, arg.ID, arg.Assistant)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Assistant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
