// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, chat_id, role, name, content, tool_call_id, tool_call_name, tool_call_arguments, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id, chat_id, role, name, content, tool_call_id, tool_call_name, tool_call_arguments, created_at
`

type CreateMessageParams struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	ChatID            pgtype.UUID `db:"chat_id" json:"chat_id"`
	Role              string      `db:"role" json:"role"`
	Name              pgtype.Text `db:"name" json:"name"`
	Content           pgtype.Text `db:"content" json:"content"`
	ToolCallID        pgtype.Text `db:"tool_call_id" json:"tool_call_id"`
	ToolCallName      pgtype.Text `db:"tool_call_name" json:"tool_call_name"`
	ToolCallArguments pgtype.Text `db:"tool_call_arguments" json:"tool_call_arguments"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChatID,
		arg.Role,
		arg.Name,
		arg.Content,
		arg.ToolCallID,
		arg.ToolCallName,
		arg.ToolCallArguments,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Name,
		&i.Content,
		&i.ToolCallID,
		&i.ToolCallName,
		&i.ToolCallArguments,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteMessagesByChatID = `-- name: DeleteMessagesByChatID :exec
DELETE FROM messages WHERE chat_id = $1
`

func (q *Queries) DeleteMessagesByChatID(ctx context.Context, chatID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesByChatID, chatID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, chat_id, role, name, content, tool_call_id, tool_call_name, tool_call_arguments, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Name,
		&i.Content,
		&i.ToolCallID,
		&i.ToolCallName,
		&i.ToolCallArguments,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageCount = `-- name: GetMessageCount :one
SELECT COUNT(*) FROM messages WHERE chat_id = $1
`

func (q *Queries) GetMessageCount(ctx context.Context, chatID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMessageCount, chatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesByChatID = `-- name: GetMessagesByChatID :many
SELECT id, chat_id, role, name, content, tool_call_id, tool_call_name, tool_call_arguments, created_at FROM messages 
WHERE chat_id = $1 
ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByChatID(ctx context.Context, chatID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Name,
			&i.Content,
			&i.ToolCallID,
			&i.ToolCallName,
			&i.ToolCallArguments,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages 
SET content = $2
WHERE id = $1
RETURNING id, chat_id, role, name, content, tool_call_id, tool_call_name, tool_call_arguments, created_at
`

type UpdateMessageParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Content pgtype.Text `db:"content" json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Name,
		&i.Content,
		&i.ToolCallID,
		&i.ToolCallName,
		&i.ToolCallArguments,
		&i.CreatedAt,
	)
	return i, err
}
