// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Title     pgtype.Text        `db:"title" json:"title"`
	Assistant pgtype.Text        `db:"assistant" json:"assistant"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Message struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ChatID            pgtype.UUID        `db:"chat_id" json:"chat_id"`
	Role              string             `db:"role" json:"role"`
	Name              pgtype.Text        `db:"name" json:"name"`
	Content           pgtype.Text        `db:"content" json:"content"`
	ToolCallID        pgtype.Text        `db:"tool_call_id" json:"tool_call_id"`
	ToolCallName      pgtype.Text        `db:"tool_call_name" json:"tool_call_name"`
	ToolCallArguments pgtype.Text        `db:"tool_call_arguments" json:"tool_call_arguments"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
