// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteChat(ctx context.Context, id pgtype.UUID) error
	DeleteMessage(ctx context.Context, id pgtype.UUID) error
	DeleteMessagesByChatID(ctx context.Context, chatID pgtype.UUID) error
	GetChat(ctx context.Context, id pgtype.UUID) (Chat, error)
	GetChatSummaries(ctx context.Context) ([]GetChatSummariesRow, error)
	GetChats(ctx context.Context) ([]Chat, error)
	GetMessage(ctx context.Context, id pgtype.UUID) (Message, error)
	GetMessageCount(ctx context.Context, chatID pgtype.UUID) (int64, error)
	GetMessagesByChatID(ctx context.Context, chatID pgtype.UUID) ([]Message, error)
	UpdateChat(ctx context.Context, arg UpdateChatParams) (Chat, error)
	UpdateChatAssistant(ctx context.Context, arg UpdateChatAssistantParams) (Chat, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
